### ISSUE TITLE
iconfont_convert version too low?

### ISSUE THREAD

**Issue by disonwei** [Wkan/iconfont_convert#1]
➜ iconfont_convert -c iconfont.yaml
iconfont_convert 1.0.0 requires the Flutter SDK, which is unsupported for global executables.

**Comment by disonwei** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.3, on macOS 13.5.2 22G91 darwin-arm64, locale zh-Hans-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.81.1)
[✓] Connected device (3 available)
[✓] Network resources

Do you support this version?

**Comment by Wkan** [comment]
I reproduced the issue you mentioned.

Did you use version A of Flutter to run `flutter pub global activate iconfont_convert` within the backticks, and then switch to version B of Flutter to run `iconfont_convert -c iconfont.yaml`?

I reproduced the issue you encountered in this way. Try RERUN `flutter pub global activate iconfont_convert` to see if it resolves the problem.
